### ISSUE TITLE
Upgrading to newer versions, dependencies - solved

### ISSUE THREAD

**Issue by robertZaufall** [piomin/sample-terraform-kubernetes-argocd#1]
Thanks for your awesome posting on this topic. Today I got it running on Azure Kubernetes and local Minikube.

From **argocd** helm chart version 5.0.0 onwards the 'values' block does not support 'additionalApplications' any more. There exists now an **argocd-apps** chart for that. On the other hand I had to fill in some dependencies, because I got errors during olm_apply.

Here are my changes in the tf-file:

```
data "kubectl_file_documents" "crds" {
  content = file("olm/crds.yaml") 
}

resource "kubectl_manifest" "crds_apply" {
  for_each          = data.kubectl_file_documents.crds.manifests
  yaml_body         = each.value
  wait              = true
  server_side_apply = true
}

data "kubectl_file_documents" "olm" {
  content = file("olm/olm.yaml")
}

resource "kubectl_manifest" "olm_apply" {
  depends_on = [kubectl_manifest.crds_apply]
  for_each   = data.kubectl_file_documents.olm.manifests
  yaml_body  = each.value
  wait       = true
}

resource "helm_release" "argocd" {
  name             = "argocd"
  repository       = "https://argoproj.github.io/argo-helm"
  chart            = "argo-cd"
  namespace        = "argocd"
  version          = "5.5.8"
  create_namespace = true

  depends_on = [kubectl_manifest.olm_apply]
}

resource "helm_release" "argocd_apps" {
  name             = "argocd-apps"
  repository       = "https://argoproj.github.io/argo-helm"
  chart            = "argocd-apps"
  namespace        = "argocd"
  
  values = [
    file("argocd/application.yaml")
  ]

  depends_on = [helm_release.argocd]
}
```

Also the structure of the application.yaml-content used by the argocd-apps chart has to be slightly changed:

```
applications: 
  - name: cluster-config
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/piomin/sample-terraform-kubernetes-argocd.git
      targetRevision: HEAD
      path: manifests/cluster
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
    syncPolicy:
      automated:
        prune: false
        selfHeal: false
```

One more hint: when deploying on Azure Kubernetes only four storage disks are allowed using a cheaper one B2s, B2ms [(B-series sizing in AKS)](https://azure.microsoft.com/en-us/blog/introducing-burstable-vm-support-in-aks/). So I reduced Kafka to two replicas, Zookeeper to one.
